version: '3'
services:
  graphql:
    build: 
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "${APP_PORT}:4001"
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
    driver: "bridge"